from github import Github
from agent.state import AgentState
from config import GITHUB_TOKEN


def pr_reporter(state: AgentState) -> AgentState:
    """Post a structured report as a GitHub PR comment."""
    error_analysis = state["error_analysis"]
    blame_result = state["blame_result"]
    proposed_fix = state["proposed_fix"]
    validation_result = state["validation_result"]
    repo_full_name = state["repo_full_name"]
    pr_number = state.get("pr_number")

    # Build the report
    confidence = proposed_fix.get("confidence", 0)
    confidence_emoji = "🟢" if confidence >= 0.8 else "🟡" if confidence >= 0.6 else "🔴"

    report = f"""## 🤖 CI/CD Agent Report

### ❌ Build Failure Analysis
**Error:** {error_analysis.get('error_message', 'Unknown')}
**File:** `{error_analysis.get('file', 'unknown')}` (line {error_analysis.get('line_number', '?')})
**Root Cause:** {error_analysis.get('root_cause_category', 'unknown')}
**Summary:** {error_analysis.get('summary', '')}

### 🔍 Blame Trace
**Commit:** [`{blame_result.get('commit_sha', 'unknown')}`]({blame_result.get('url', '#')}) by **{blame_result.get('author', 'unknown')}**
**Message:** {blame_result.get('message', '').split(chr(10))[0]}

### 💡 Proposed Fix
**File:** `{proposed_fix.get('file', 'unknown')}`
**Confidence:** {confidence_emoji} {confidence}

```diff
- {proposed_fix.get('original_code', 'N/A')}
+ {proposed_fix.get('fixed_code', 'N/A')}
```

**Explanation:** {proposed_fix.get('explanation', '')}

### ✅ Validation
{"✅ Fix passed validation" if validation_result.get('valid') else "⚠️ Fix has issues: " + ", ".join(validation_result.get('issues', []))}

---
*Generated by CI/CD Agent 🤖*"""

    print(f"\n[PR Reporter] Report generated ({len(report)} chars)")

    # Post to GitHub PR if PR number is available
    if pr_number:
        try:
            gh = Github(GITHUB_TOKEN)
            repo = gh.get_repo(repo_full_name)
            pr = repo.get_pull(pr_number)
            pr.create_issue_comment(report)
            print(f"[PR Reporter] Comment posted to PR #{pr_number}")
        except Exception as e:
            print(f"[PR Reporter] Could not post PR comment: {e}")
    else:
        # Post as commit comment instead
        try:
            gh = Github(GITHUB_TOKEN)
            repo = gh.get_repo(repo_full_name)
            commit_sha = blame_result.get("full_sha")
            if commit_sha:
                commit = repo.get_commit(commit_sha)
                commit.create_comment(report)
                print(f"[PR Reporter] Comment posted to commit {commit_sha[:7]}")
        except Exception as e:
            print(f"[PR Reporter] Could not post commit comment: {e}")

    print("\n=== FULL REPORT ===")
    print(report)
    print("===================\n")

    return {**state, "report": report}
